### ISSUE TITLE
Python 3 incompatible

### ISSUE THREAD

**Issue by penguinolog** [inorton/junit2html#18]
Start in Python 3 venv and got traceback (last strings):
```  File "/usr/lib64/python3.5/cgi.py", line 1056, in escape
    s = s.replace("&", "&amp;") # Must be done first!
TypeError: a bytes-like object is required, not 'str'
```
This means, that it's Python 3 incompatible.

**Comment by inorton** [comment]
Hmm, I'll try to find some time to work on this.

**Comment by timj** [comment]
My PR #20 fixes the basic problem in the simplest way. Python 3 makes this all easy because it's natively unicode. The problem with python 2 is that the XML parser returns unicode objects but the `text()` method converts those to bytes and `cgi.escape()` does not work on bytes. On python 3 the encoding should not happen and the file output should not be binary mode.
